SAMMaru5/SAMMaruServer

- src/main/java/com/sammaru5/sammaru/controller/user/UserController.java
- src/main/java/com/sammaru5/sammaru/domain/UserEntity.java
- src/main/java/com/sammaru5/sammaru/dto/UserDTO.java
- src/main/java/com/sammaru5/sammaru/repository/UserRepository.java
- src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
resolve #6 
기수별 멤버 조회 API 추가합니다.
UserEntity와 UserDTO에 generation(Integer) 필드 추가하여 기수에 대한 정보를 가지게 하였습니다.
generation을 통해 멤버 조회가 가능하도록 했습니다.
> feat : 기수별 멤버 조회 (#6)

- src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
resolve #32 
ArticleEntity에서 ArticleDTO로의 변환 과정에서 일부 필드가 적용되지 않는 문제 수정
copyProperties를 사용하지 않고 해당 필드에 직접 값 주입
> fix : ArticleEntity에서 ArticleDTO로의 변환 과정에서 일부 필드가 적용되지 않는 문제 수정(#32)

- src/main/java/com/sammaru5/sammaru/SammaruApplication.java
- src/main/java/com/sammaru5/sammaru/domain/Article.java
- src/main/java/com/sammaru5/sammaru/domain/BaseTime.java
- src/main/java/com/sammaru5/sammaru/domain/Board.java
- src/main/java/com/sammaru5/sammaru/domain/Comment.java
- src/test/java/com/sammaru5/sammaru/repository/ArticleRepositoryTest.java
resolve #27 
hibernate에 의존하지 않기 위해서 진행한 리팩토링
- @CreationTimestamp 를 @CreatedDate로 변경하면서 JpaAuditing 추가
- 관련 테스트 코드 작성
<br>
- @CreatedDate, @LastModifiedDate를 field로 갖는 공통모듈인 BaseTime 추상화 클래스 생성 후 Article, Comment에 상속
> refactor: @CreationTimestamp 를 @CreatedDate로 변경하면서 JpaAuditing 추가

- src/main/java/com/sammaru5/sammaru/domain/IndelibleBoardName.java
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/service/board/BoardRemoveService.java
resolve #25 
중요 게시판의 자료 삭제를 방지하기 위해 중요 게시판은 삭제가 되지 않도록 함
중요 게시판 삭제시 BOARD_NOT_REMOVE 에러의 Exception을 발생시킴
> feat : 중요 게시판 삭제할때 Exception 발생

- src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
- src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
resolve #50 
게시글 조회 시 첨부된 파일이 조회되지 않는 현상이 있었습니다.
게시글 조회 시 파일(`left join`)과 작성자(`join`)를 모두 join하여 한 번에 가져옵니다.
만약, 파일이 없다면 빈 `ArrayList`를 반환합니다.
파일을 `left join`한 이유는 게시글에 첨부된 파일이 존재하지 않을때도 게시글을 가져와야하기 때문에 사용하였습니다.
> fix : 게시글 조회 시 첨부된 파일과 작성자를 한번에 볼 수 있도록 Query 수정

- build.gradle
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/repository/UserRepository.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserTempPasswordService.java
- src/main/java/com/sammaru5/sammaru/web/controller/auth/AuthController.java
- src/main/resources/application.yml
resolve #44 
비밀번호를 잊어버렸을시, 메일을 입력하면 해당 계정에 대한 임시 비밀번호를 메일로 보내주는 기능
- `SecureRandom`을 활용한 임시 비밀번호 생성
- `JavaMailSender`를 통한 메일 전송 기능 구현
- 동아리 gmail 계정 생성
<br>
- 회원가입, 회원 정보 수정 시에 이메일 중복 여부 체크 기능 추가
> feat: 임시 비밀번호를 메일로 받아볼 수 있는 기능 추가

- src/main/java/com/sammaru5/sammaru/domain/SearchSubject.java
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
- src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
- src/test/java/com/sammaru5/sammaru/repository/ArticleRepositoryTest.java
- src/test/java/com/sammaru5/sammaru/repository/ArticlesSearchTest.java
resolve #46 
게시글 검색 기능 추가
- 전체, 게시판별로 다음과 같은 기준으로 검색할 수 있습니다.
- 글쓴이 username
- 글쓴이 학번
- 제목+내용
- 제목
- 내용
- 관련 테스트 케이스 추가
이번에 추가한 articleRepository에서 메소드 이름이 너무 긴 것 같은데 어떻게 하는게 좋을까요?
예를 들어서 `findArticlesWithFilesAndUserByBoardAndKeywordForArticleContent
` -> `searchArticlesByBoardAndContent` 이런 식으로 줄여서 쓰는게 더 좋을까요?
> feat: 게시글 검색 기능 추가

- src/main/java/com/sammaru5/sammaru/domain/User.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/web/request/UserRequest.java
resolve #58
회원 정보 수정 요청이 들어올때 수정되지 않은 항목은 기존 값으로 전달되는 경우를 기준으로 동작하도록 수정
- `UserModifyService.modifyUser()` 수정
- email 중복 검사에 기존 email과 동일한지 검사하는 조건문 추가
- 항목별로 `null`인지 검사하는 조건문들 제거
- `UserRequest` class에 `@NotBlank` 추가
> fix: 회원 정보 수정 기능 client에 맞게 수정 (#58)

- src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
resolve #62 
임시 회원은 메인페이지를 볼 수 없었던 문제 수정
자기 자신 회원 정보 API의 호출 등급을 임시 회원도 사용할 수 있도록 변경
> fix : 자기 자신의 회원 정보 조회 API를 임시 회원도 사용할 수 있게 변경

- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/web/controller/exception/ExceptionController.java
resolve #68 
`Custom Exception`이 발생했을때 `http reponse`의 `status code`가 항상 `200 OK`로 반환됌
`ExceptionHandler`에서 반환값으로 `ApiResult` 대신 `ResponseEntity`를 반환하도록 수정
기존에 `NullPointerException`이나 `AccessDeniedException` 등을 통해 처리되던 오류들이 `CustomException`을 통해 처리되도록 수정되었기 때문에
`ExceptionController`에서 `NullPointerException`이나 `AccessDeniedException` 등의 Exception handler가 더 이상 필요하지 않은 것 같은데 제거하는게 어떨까요?
아니면 만약을 대비해서 이 부분도 적절한 `http status code`를 반환하도록 수정하는게 좋을까요?
> fix: CustomException 발생시 Http Response의 Http Status Code가 해당 exception과 일치하도록 수정

- src/main/java/com/sammaru5/sammaru/config/jwt/TokenProvider.java
resolve #80
로그인 관련 오류 해결
`TokenProvider` 클래스에서 `ACCESS_TOKEN_EXPIRE_TIME `랑 `REFRESH_TOKEN_EXPIRE_TIME` 값을 설정 파일에서 `@Value`를 통해 가져오는 방식을 사용하는데 static 필드로 되어있어서 정상적으로 값이 주입되지 않는 문제가 발생하여 이 부분을 수정함
수정 전에 spring을 실행시켜보면 다음과 같은 로그 메시지를 확인할 수 있다.
실제로 `REFRESH_TOKEN_EXPIRE_TIME` 값을 출력해보면 설정 파일의 값이 아닌 0이 들어가 있는 것을 확인할 수 있다
> bug: Value Annotation 사용 필드에서 static 제거 (#80)

- src/main/java/com/sammaru5/sammaru/repository/UserRepository.java
- src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
- src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
resolve #75 
username으로 회원 정보 조회 해결 
- `findByUsernameContaining`을 이용해 검색 글자가 포함된 user들을 조회할 수 있도록 함.
- `List` 데이터형을 이용하여 검색 결과를 List 형태로 출력하도록 함.
> fix: username으로 검색 시, 검색 글자가 포함된 모든 users를 List로 출력되도록 수정

- src/main/java/com/sammaru5/sammaru/config/jwt/JwtAuthenticationFilter.java
resolve #84
AccessToken을 확인하는 방식도 header에서 Cookie로 바뀌었다고 착각해서 변경했던 부분 수정
다시 header에서 accessToken 값을 확인하도록 변경
> fix: request가 들어왔을 때 AccessToken 값을 Cookie가 아닌 header에서 확인하도록 변경

- src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
- src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
- src/test/java/com/sammaru5/sammaru/repository/ArticleRepositoryTest.java
- src/test/java/com/sammaru5/sammaru/repository/ArticlesSearchTest.java
resolve #82 
Client 측에서 게시판 pagination 관련 기능을 제작하기 위해 필요하다고 요청한 기능
- 게시글을 Paging 하는 요청의 경우, List 대신 Page 객체를 반환함으로써 총 페이지 수, 총 게시글 수 등의 정보를 Client 측에서 확인할 수 있도록 수정
- query parameter로 페이지 당 게시글 개수를 입력받을 수 있도록 수정
- /no-permit/api/boards/{boardId}/pages/{pageNum}
- /no-permit/api/boards/{boardId}/searchResult/pages/{pageNum}
- /no-permit/api/boards/searchResult/pages/{pageNum}
> Swgger에서 변경된 API들 참고
기존에는 게시글만 response에 담겨있었는데 다음과 같이 수정되었다.
1. 게시글은 content 안에 묶여서 들어간다.
2. 그리고 reponse 안에 다음과 같은 항목들이 추가되었다.
- `totalPage` : 총 페이지 수
- `totalElements` : 총 게시글 수
- `last` : 마지막 페이지인지 여부
- `size` : 한 페이지 당 게시글 수
- `number` : 현재 페이지 number, 0부터 시작
> feat: 페이징 API 기능 추가

- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
resolve #92
기존에 게시글이 없는 게시판을 조회하면 400 error가 발생하도록 했는데, 이는 부적절하다고 판단됌
빈 게시판을 조회하더라도 400 error가 발생하지 않고 200 OK로 빈 배열을 반환하도록 수정
> fix: 빈 게시판을 조회하더라도 400 error가 발생하지 않고 200 OK로 빈 배열을 반환하도록 수정

- src/main/java/com/sammaru5/sammaru/config/SwaggerConfig.java
- src/main/java/com/sammaru5/sammaru/service/user/UserLogoutService.java
- src/main/java/com/sammaru5/sammaru/web/controller/auth/AuthController.java
resolve #110
로그아웃 API 추가
- 로그아웃 요청시 Redis에 저장된 RefreshToken 삭제
> AccessToken은 만료되기 전까진 따로 비활성화할 수 있는 방법이 없음.
> AccessToken을 일일히 따로 저장해서 관리한다면 가능하겠지만 리소스가 많이 사용될테고, jwt의 취지에 맞지 않음
- 로그아웃 요청시 set-cookie에 max-age를 0으로 설정해서 보냄으로써 클라이언트에 저장된 쿠키가 삭제되도록 구현
- Swagger에서 테스트시 Authorization 헤더 설정할 수 있는 기능 추가
Swagger UI에서 `Authorize` 버튼 클릭 후
그림과 같이 AccessToken 앞에 `Bearer `를 붙여서 입력하고 `Authorize` 버튼을 눌러서 사용하시면 됩니다.
> feat: 로그아웃 API 추가

- src/main/java/com/sammaru5/sammaru/web/dto/CommentDTO.java
resolve #112 
* api : /api/boards/{boardId}/articles/{articleId}/comments 요청시 id와 content만 데이터 제공*
* 댓글 작성자, 작성일자도 제공
* 작성자, 작성일자 제공하게끔 CommentDTO 수정
> fix: CommentDTO수정 (createDt, author추가)

- src/main/java/com/sammaru5/sammaru/repository/CommentRepository.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
- src/test/java/com/sammaru5/sammaru/service/article/ArticleRemoveServiceTest.java
resolve #120
게시글 삭제 오류 수정
- 게시글을 삭제하기 전 해당 게시글의 댓글부터 모두 삭제하도록 수정
- 관련 테스트 추가
`cascadingType`을 통해서 설정해주는게 코드가 더 간결할 것 같지만, 아직 공부가 필요한 부분이라 추후에 수정할 예정
> fix: 게시글 삭제하기전 관련 댓글부터 삭제하도록 수정

- src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
- src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
resolve #118 
게시글 생성 및 수정 API에서 DTO 반환으로 수정하여, 해당 데이터가 필요할 시 수정 요청 response에서 변경된 객체를 꺼내서 쓰면 되기에 네트워크 요청을 추가로 보낼 필요가 없다는 장점이 있다.
- 게시글 생성 및 수정 API에서 DTO를 반환하도록 수정 (id -> DTO)
> refactor: 게시글 생성 및 수정 API의 반환을 DTO로 변경

- src/main/java/com/sammaru5/sammaru/service/board/BoardSearchService.java
- src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
resolve #128 
게시판 조회 서비스 이름 변경 
- 게시판 조회 서비스 이름을 `BoardStatusService`에서 `BoardSearchService`로 변경한다.
> refactor: 게시판 조회 서비스 이름 변경

- src/main/java/com/sammaru5/sammaru/domain/User.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/web/request/UserRequest.java
resolve #114 
유정보 수정 API에서 학번(student_id)도 변경 가능하게끔 수정
UserRequest, modifyUserInfo 메서드에 student_id 추가
> fix : 정보수정 API 에서 student_id 수정 가능하게 변경

- src/main/java/com/sammaru5/sammaru/service/board/BoardRegisterService.java
resolve #145
게시판 등록 서비스내의 트랜잭션 단위안에서 예외 처리하도록 설정
- `validateDuplicateBoard( )` 메서드 삭제
- `addBoard( )` 메서드 내에서 게시판 중복 이름 존재 시 예외 처리하도록  설정
> refactor: 게시판 등록 서비스내의 트랜잭션 단위안에서 예외처리하도록 설정

- build.gradle
- src/main/java/com/sammaru5/sammaru/domain/Comment.java
- src/main/java/com/sammaru5/sammaru/domain/User.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
- src/test/java/com/sammaru5/sammaru/WithMockCustomUser.java
- src/test/java/com/sammaru5/sammaru/service/article/ArticleSearchServiceTest.java
- src/test/java/com/sammaru5/sammaru/web/controller/comment/CommentControllerTest.java
resolve #152 
관리자는 타인의 댓글을 삭제할 수 있도록 수정. 관리자용 댓글 삭제 메소드 추가
- 기존 테스트 코드 리팩토링
- 관리자는 타인의 댓글을 삭제할 수 있는지 확인하는 테스트 코드 추가
- 관리자는 타인의 댓글을 삭제할 수 있도록 기존의 로직 수정
> fix: 관리자는 타인의 댓글을 삭제할 수 있도록 기능 수정

- src/main/java/com/sammaru5/sammaru/config/EmbeddedRedisConfig.java
resolve #161 
여러 `@SpringBootTest`를 실행하다보면 이미 `redisServer`가 실행중인데, `redisServer.start()`를 실행하면서 포트 충돌이 발생하는 경우가 생긴다.
하지만 이때, 다른 `@SpringBootTest`에서 생성한 `redisServer`를 직접적으로 조작할 수는 없어도 통신하는 것은 가능하기 때문에 생성에 실패하더라도 테스트를 수행하는데는 문제가 없다.
try-catch 문으로 `redisServer.start()` 부분에서 발생하는 에외 처리
https://github.com/chisan01/TIL/blob/main/project-record/sammaru-server/embedded-redis.md#embedded-redis-%ED%8F%AC%ED%8A%B8-%EC%B6%A9%EB%8F%8C-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0
> bug: 테스트시 redisServer 재생성으로 인한 포트충돌 문제 해결

- src/main/java/com/sammaru5/sammaru/web/dto/CommentDTO.java
- CommentDTO 에 userId 필드 추가
resolve #176 
* 댓글 목록 조회시 사용자 이름이 같으면 구분할 수 없음
* 댓글 목록 조회시 userId도 함께 반환
* CommentDTO 에 userId 필드 추가
> fix : 댓글목록 조회시 userId도 함께 반환

- src/main/java/com/sammaru5/sammaru/config/jwt/JwtAuthenticationFilter.java
- src/main/java/com/sammaru5/sammaru/config/jwt/JwtToken.java
- src/main/java/com/sammaru5/sammaru/config/jwt/TokenProvider.java
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/service/user/UserLoginService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserReissueService.java
- src/main/java/com/sammaru5/sammaru/web/controller/auth/AuthController.java
- src/main/java/com/sammaru5/sammaru/web/controller/auth/TokenRequest.java
- src/main/java/com/sammaru5/sammaru/web/dto/JwtDto.java
- src/main/resources/application-local.yml
resolve #185 
login, reissue, logout 로직 변경
login, reissue, logout 로직 변경
- 기존 access token, refresh token 두 개를 body로 실어보내는 로직에서 access token만 body로 보내고 refresh token은 httponly, secure, samesite 옵션을 가진 cookie로 담아 보내도록 수정했습니다.
application-local.yml에는 `sammaru.cookie.secure` 값이 **_false_** 로 설정되어있는데
application-prod.yml에도 `sammaru.cookie.secure` 를 추가해주시고 값을 **_true_** 설정해주세요(아래 사진 참고)
> refactor: login, reissue, logout 로직 변경 (#185)

- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
- src/main/java/com/sammaru5/sammaru/web/request/UserInfoModifyRequestDto.java
resolve #188 
기존 회원 정보 api deprecate, 관리자용 회원정보 수정 api 추가
기존 회원 정보 api deprecate, 관리자용 회원정보 수정 api 추가
> fix: 기존 회원 정보 api deprecate, 관리자용 회원정보 수정 api 추가

- src/main/java/com/sammaru5/sammaru/config/EmbeddedRedisConfig.java
- src/main/java/com/sammaru5/sammaru/config/RedisConfig.java
- src/main/java/com/sammaru5/sammaru/domain/Article.java
- src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
- src/main/java/com/sammaru5/sammaru/util/CacheKey.java
- src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
- src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
- src/main/java/com/sammaru5/sammaru/web/dto/ArticleDetailDTO.java
- ArticleRepository
- findPrevArticle()
- findNextArticle()
- ArticleDetailDTO 생성
resolve #179 
게시글 상세 api에 해당 게시글의 이전 게시글, 다음 게시글에 대한 정보 제공
* 같은 board에 속하는 게시글에서 요청된 게시글 기준으로 최소값, 최대값을 이전글, 다음글에 매핑하여 제공
*  이전글, 다음글이 없을 경우 null
DB<br>
이전글이 존재하지 않는 경우 <br>
다음글이 존재하지 않는 경우 <br>
같은 board에 속하는 다음글 이전글 제공
> fix : 게시글 상세에 이전, 게시글 id 도 함께 제공

- src/main/java/com/sammaru5/sammaru/config/WebSecurityConfig.java
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/service/user/UserEmailVerifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
- src/main/java/com/sammaru5/sammaru/util/CacheKey.java
- src/main/java/com/sammaru5/sammaru/util/redis/RedisUtil.java
- src/main/java/com/sammaru5/sammaru/web/controller/auth/AuthController.java
- src/main/java/com/sammaru5/sammaru/web/request/VerificationCodeRequest.java
resolve #189 
올바르지 않은 이메일로 가입한 사례 존재함
회원가입시 이메일에 대한 인증 기능 추가
- /auth/send 
- 해당 email로 인증코드 전송
- /auth/verify
- 인증코드를 통한 이메일 검증
- 회원가입시 인증받은 이메일인지 검증하는 로직 추가
인증코드, 인증된 이메일 저장은 redis를 활용했습니다.
> fix: 회원가입시 이메일에 대한 인증 기능 추가

- src/main/java/com/sammaru5/sammaru/service/user/UserEmailVerifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
- /auth/signUp 후 redis 에서 삭제되던 인증코드를 /auth/verify 후 삭제로 변경
- 인증코드 유효 이슈 해결
resolve #197 
이전에 발급된 인증코드가 유효한 이슈에 대한 해결
/auth/signUp 후 redis 에서 삭제되던 인증코드를 /auth/verify 후 삭제로 변경
> fix : 인증코드 유효 이슈 해결

- src/main/java/com/sammaru5/sammaru/config/AsyncConfig.java
- src/main/java/com/sammaru5/sammaru/service/user/UserEmailVerifyService.java
resolve #199 
인증번호 요청후 긴 응답시간의 개선을 위한 작업입니다.
* @Async annontation 사용을 위한 AsyncConifg 클래스 추가
*  UserEmailVerifyService.sendVerificationCode @Async annotation 추가, 다른 thread로 실행
비동기 처리 전
비동기 처리 후
> fix : 이메일 전송 비동기 처리를 통한 응답 속도 개선
