- src/main/java/com/sammaru5/sammaru/controller/comment/CommentController.java
resolve #1 
Swagger에서 해당 response 결과 값을 명확하게 확인하기 힘들어 refactoring 진행했습니다.
Comment Controller에서 Wild Card 리턴 타입을 리턴 타입을 특정하도록 변경했습니다.
> refactor : change return type wild card to specific type

- src/main/java/com/sammaru5/sammaru/controller/article/ArticleController.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
resolve #3 
게시글 관련 기능에서 유저를 가져올 때 500 에러 발생 해결
게시글 관련 기능에서 Authentication 객체를 사용한 부분을 모두 custom으로 만든 AuthUser로 변경하였습니다.
> [fix] change authentication to custom auth user annotation (#3)

- src/main/java/com/sammaru5/sammaru/controller/article/ArticleController.java
resolve #10 
원치않은 API 권한 수정
해당 API에 맞게 권한 수정
> fix : change authority in proper api that file download api (#5)

- src/main/java/com/sammaru5/sammaru/domain/ArticleEntity.java
- src/main/java/com/sammaru5/sammaru/repository/ArticleRepository.java
resolve #{9}
게시글 조회시 연관된 파일도 함께 조회합니다
article과 file을 양방향 매핑하였고, 이때 article에서 files가 OneToMany관계가 되므로 N+1문제 해결과 페이징을 위해 Batchsize를 지정했습니다.
> feat : When viewing articles, related files are also searched (#6)

- src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
- src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
resolve #34 
File이 존재하지 않는 Article 조회 시 조회가 안되는 문제 수정
Fetch join을 사용하지 않고 해당 Article을 먼저 조회 후 File을 따로 조회
> fix : file이 존재하지 않는 article 조회 시 조회가 안되는 문제 수정

- src/main/java/com/sammaru5/sammaru/exception/CustomException.java
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/exception/InvalidRefreshTokenException.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentSearchService.java
- src/main/java/com/sammaru5/sammaru/service/file/FileRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/file/FileStatusService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserReissueService.java
- src/main/java/com/sammaru5/sammaru/web/controller/exception/ExceptionController.java
resolve #18
CustomException 추가 및 Enum으로 ErrorCode 관리하도록 변경
-> 상세한 예외 정보 제공 및 에러 응집도 향상
- ErrorCode Enum 추가
- CustomException 추가
- ExceptionController에 handleCustomException 추가
- Service에서 CustomException 사용하도록 수정
<br>
- 추후 Board 관련 Service들 CustomException 사용하도록 수정 예정
> [REFACTOR] CustomException 추가 및 Enum으로 ErrorCode 관리하도록 변경

- src/main/java/com/sammaru5/sammaru/config/WebSecurityConfig.java
- src/main/java/com/sammaru5/sammaru/util/OverAdminRole.java
- src/main/java/com/sammaru5/sammaru/util/OverMemberRole.java
- src/main/java/com/sammaru5/sammaru/util/OverTempRole.java
- src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
- src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
- src/main/java/com/sammaru5/sammaru/web/controller/comment/CommentController.java
- src/main/java/com/sammaru5/sammaru/web/controller/schedule/ScheduleController.java
- src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
- src/main/java/com/sammaru5/sammaru/web/request/RoleRequest.java
resolve #28 
유저의 역할마다 사용할 수 있는 API를 제한하여 역할 분리
역할에 따른 메서드 권한 접근을 제한하는 커스텀 어노테이션을 만들고, API에 적용
> feat : 유저의 역할마다 사용할 수 있는 기능 제한

- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
- src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
- src/main/java/com/sammaru5/sammaru/web/dto/UserDTO.java
resolve #45 
단일 회원 정보 조회 API 추가
단일 회원 정보 조회 API 추가 및 UserController 메소드들의 Return Type을 Wild Card에서 명확한 Return Type으로 변경
> feat : userId로 단일 회원 정보 조회 API 추가

- src/main/java/com/sammaru5/sammaru/domain/User.java
resolve #64 
UserAuthority가 DB에서 숫자로 관리된다면 유지보수성 저하
UserAuthority에 @Enumerated(value = EnumType.STRING) 적용
> refactor : UserAuthority에 @Enumerated(value = EnumType.STRING) 적용

- src/main/java/com/sammaru5/sammaru/domain/Article.java
- src/main/java/com/sammaru5/sammaru/domain/Comment.java
resolve #67
- content type 수정 
- Article & Comment의 content type을 (varchar->text)로 수정함
> refactor: content type (varchar->text)로 수정

- src/main/java/com/sammaru5/sammaru/domain/Article.java
- src/main/java/com/sammaru5/sammaru/domain/Board.java
- src/main/java/com/sammaru5/sammaru/domain/Comment.java
- src/main/java/com/sammaru5/sammaru/domain/File.java
- src/main/java/com/sammaru5/sammaru/domain/Schedule.java
resolve #66
Entity 중 id관련 수정 
- id 값 generateValue strategy IDENTITY로 수정함
> refactor: id값 generateValue strategy IDENTITY로 수정

- .gitignore
- Dockerfile.prod
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
resolve #69 
1차 application.yml 분리
- application.yml을 로컬, 개발, 배포 환경에 맞게 분리
- jwt키같은 민감 정보는 .gitignore에 추가하고 값을 변경하였음
> refactor : 1차 application.yml 분리

- src/main/java/com/sammaru5/sammaru/config/jwt/JwtAuthenticationFilter.java
- src/main/java/com/sammaru5/sammaru/config/jwt/TokenProvider.java
- src/main/java/com/sammaru5/sammaru/config/security/UserDetail.java
resolve #84 
인증 관련 오류 해결
- 기존에 인증에 필요한 token 값을 헤더를 통해 주고받는 방식에서 최근 쿠키를 이용해 주고받도록 변경되었는데, Server에서 여전히 token 값을 쿠키가 아닌 헤더에서 꺼내오도록 되어있어서 수정함
- authentication을 생성할때 `User` 클래스의 `studentId`를 사용하는데 `UserDetail.getUsername()` 메소드에서 `User` 클래스의 `username`을 반환하도록 되어있어서 수정함
- 인증을 할 때 Spring Security에서 기본적으로 제공하는 `UserDetails`가 아닌 해당 클래스를 상속받은 `UserDetail`을 사용하는데, JWT token 값으로부터 authentication을 사용할때 `UserDetails`를 principal로 사용하면서 문제가 발생해서 이를 수정함
> bug: 인증 관련 오류 해결

- src/main/java/com/sammaru5/sammaru/web/request/PointRequest.java
resolve #95 
유저 포인트 추가할 때 500 에러 해결
- `@NotBlank`를 `@NotNull`로 수정함 
- NotBlank는 `Long` data type을  검사하지 못함 
https://bepoz-study-diary.tistory.com/242
> fix: 유저 포인트 추가할 때 500 에러 해결

- src/main/java/com/sammaru5/sammaru/domain/User.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
- src/main/java/com/sammaru5/sammaru/web/request/GenerationRequest.java
resolve #88
기수 설정 기능 추가
- 관리자 권한으로 유저의 기수 변경 기능
> feat: 기수 설정 기능 추가

- src/main/java/com/sammaru5/sammaru/repository/UserRepository.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
- src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
- src/main/java/com/sammaru5/sammaru/web/controller/comment/CommentController.java
- src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
resolve #98 
AuthUser Anntotaion을 통해 받아온 유저 정보에 학번과 권한을 제외한 정보가 없어서 발생한 오류 해결
- article, commit 관련  user 정보 DB에서 가져오도록 수정 
- user 정보 관련 메소드에서  user의 studentId를 통해 user 정보 DB 가져오도록 수정 
- UserSearchService에서 findUserByStudentId 메소드 생성
- UserRepository에서 findByStudentId 메소드 생성  
- Dirty Checking을 통한 refactoring
> bug: AuthUser Anntotaion을 통해 받아온 유저 정보에 학번과 권한을 제외한 정보가 없어서 발생한 오류 해결

- src/main/java/com/sammaru5/sammaru/domain/User.java
- src/main/java/com/sammaru5/sammaru/web/dto/UserDTO.java
- src/main/java/com/sammaru5/sammaru/web/request/UserRequest.java
resolve #91
학년 정보 변수 생성 및 설정 기능 추가
- 학년 정보 변수 `grade` 생성
- 회원정보수정에서 학년 정보 수정할 수 있는 기능 추가
> feat: 학년 정보 변수 생성 및 설정 기능 추가

- src/main/java/com/sammaru5/sammaru/config/jwt/TokenProvider.java
- src/main/java/com/sammaru5/sammaru/config/security/SecurityUtil.java
- src/main/java/com/sammaru5/sammaru/config/security/UserDetail.java
- src/main/java/com/sammaru5/sammaru/domain/User.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
- src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
- src/main/java/com/sammaru5/sammaru/web/controller/comment/CommentController.java
- src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
resolve #86 
JWT을 이용해서 authentication을 생성할때 DB 조회를 하지 않도록 수정하면서, `@AuthUser`를 통해 가져온 User 객체의 정보가 불완전함
따라서 회원 정보 조회시 회원 정보가 제대로 반환되지 않는 오류 발생
본인의 회원 정보 조회시 DB에서 해당 정보를 가져오도록 수정
> bug: 본인의 회원정보 조회시 DB에서 해당 정보를 가져오도록 수정

- build.gradle
- src/main/java/com/sammaru5/sammaru/config/RedisConfig.java
- src/main/java/com/sammaru5/sammaru/domain/Article.java
- src/main/java/com/sammaru5/sammaru/domain/ArticleLike.java
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/repository/ArticleLikeRepository.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleLikeService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
- src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
- src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
- src/test/java/com/sammaru5/sammaru/WithMockCustomUser.java
- src/test/java/com/sammaru5/sammaru/WithMockCustomUserSecurityContextFactory.java
- src/test/java/com/sammaru5/sammaru/repository/ArticleLikeRepositoryTest.java
- src/test/java/com/sammaru5/sammaru/repository/ArticleRepositoryTest.java
- src/test/java/com/sammaru5/sammaru/repository/ArticlesSearchTest.java
- src/test/java/com/sammaru5/sammaru/service/article/ArticleLikeServiceTest.java
- src/test/java/com/sammaru5/sammaru/service/article/ArticleRemoveServiceTest.java
- src/test/java/com/sammaru5/sammaru/service/article/ArticleSearchServiceTest.java
- src/test/resources/application.yml
resolve #79 
게시글 좋아요 관련 기능 추가
- 게시글 좋아요 기능 추가
- 관련 테스트 코드 추가
- 작업도중 발견한 오류들 수정
> feat: 게시글 좋아요 수정 기능 추가

- src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentSearchService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserLoginService.java
resolve #116
코드 가독성을 향상하기 위한 리팩토링
- 코드 정렬
- 복잡한 if-else 구조 간소화
> refactor: 코드 가독성 향상을 위한 리팩토링

- src/main/java/com/sammaru5/sammaru/domain/Comment.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentModifyService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentSearchService.java
- src/main/java/com/sammaru5/sammaru/web/controller/comment/CommentController.java
resolve #115 
- 댓글 수정 API 
- 댓글 수정 API 추가
> feat: 댓글 수정 API 추가

- src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleSearchService.java
- src/main/java/com/sammaru5/sammaru/service/board/BoardRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentModifyService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
- src/main/java/com/sammaru5/sammaru/web/dto/ArticleDTO.java
- src/main/java/com/sammaru5/sammaru/web/dto/BoardDTO.java
- src/main/java/com/sammaru5/sammaru/web/dto/CommentDTO.java
- src/main/java/com/sammaru5/sammaru/web/dto/ScheduleDTO.java
- src/main/java/com/sammaru5/sammaru/web/dto/UserDTO.java
resolve #121 
Service layer에서 생성자를 이용한 객체 생성 대신, 정적 팩토리 메서드를 이용한 객체 사용으로 코드 리펙토링
- Comment Service
- Article Service
- Schedule Service
- Board Service 
- User Service
위의 5가지 Service에서 정적 팩토리 메서드 사용으로 수정
> refactor: Service에서 정적 팩토리 메서드를 통해 객체 생성하도록 변경

- src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
- src/main/java/com/sammaru5/sammaru/service/comment/CommentModifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
resolve #127 
Drity Checking 적용
- 엔티티 수정 시, Dirty Checking을 적용하여 변경 감지하도록 한다.
> refactor: 엔티티 수정 시, Dirty Checking 적용

- src/main/java/com/sammaru5/sammaru/domain/Schedule.java
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleModifyService.java
- src/main/java/com/sammaru5/sammaru/web/controller/schedule/ScheduleController.java
resolve #134
일정 수정 API 필요
- 일정 수정 API 추가
> feat: 일정 수정 API 추가

- src/main/java/com/sammaru5/sammaru/repository/BoardRepository.java
- src/main/java/com/sammaru5/sammaru/repository/ScheduleRepository.java
resolve #139 
코드의 통일성을 높이고자 한다.
- Repository 어노테이션 생략
> refactor: Repository 어노테이션 생략

- src/main/java/com/sammaru5/sammaru/domain/Board.java
- src/main/java/com/sammaru5/sammaru/service/board/BoardModifyService.java
- src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
resolve #135 
게시판 수정 API 필요
- 게시판 수정 API 추가
> feat: 게시판 수정 API 추가

- src/main/java/com/sammaru5/sammaru/web/request/CommentRequest.java
- src/main/java/com/sammaru5/sammaru/web/request/ScheduleRequest.java
resolve #132
요청 파라미터 체크 위해 사용되는 어노테이션 필요
- 댓글 요청 파라미터 체크 위해 사용되는 어노테이션 추가
- 일정 요청 파라미터 체크 위해 사용되는 어노테이션 추가
> fix: 댓글 및 일정 요청 파라미터 체크 위해 사용되는 어노테이션 추가

- src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleRemoveService.java
resolve #147
예외처리 추가
- 게시글 삭제 서비스에 예외처리 코드 작성
- 일정 삭제 서비스에 예외처리 코드 작성
> fix: 게시글 및 일정 삭제 서비스에 예외처리 추가 

- src/main/java/com/sammaru5/sammaru/config/MvcConfig.java
resolve #149 
배포 서버 CORS 문제 발생
배포 서버 url을 allowedOrigins에 추가
> fix: 배포 서버 url을 allowedOrigins에 추가

- src/main/java/com/sammaru5/sammaru/service/article/ArticleLikeService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleModifyService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/article/ArticleRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/board/BoardRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/board/BoardRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/board/BoardSearchService.java
- src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/schedule/ScheduleRemoveService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserLoginService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserLogoutService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserRegisterService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserReissueService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserSearchService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserStatusService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserTempPasswordService.java
resolve #141 
Transaction 관련 성능 향상
- Article Service
- Board Service
- Comment Service
- Schedule Service
- User Service
위에 제시된 5개의 Service에 대해 
- Service Class Level에 @Transactional(readOnly=true) 작성한다.
- Service Class의 메소드 Level에 @Transactional 작성한다. (단, 변동사항이 있는 메소드에 한해)
> refactor: 성능 향상을 위한 @Transaction(readOnly=true) 작성

- build.gradle
- src/test/java/com/sammaru5/sammaru/service/article/ArticleSearchServiceTest.java
- src/test/resources/application.yml
resolve #153
테스트 환경 수정
- E2E 테스트를 위해 `rest-assured` 라이브러리 추가
- 테스트 코드는 메모리 DB를 사용하도록 변경
> 별도의 테스트 DB를 구축하지 않아도됨
- test 오류 수정
- 테스트 도중 auto_increment 초기화가 필요한 경우 `@DirtiesContext` Annotation을 사용하도록 변경
> fix: 테스트 환경 수정

- src/main/java/com/sammaru5/sammaru/web/controller/article/ArticleController.java
- src/main/java/com/sammaru5/sammaru/web/controller/board/BoardController.java
resolve #156 
게시글 검색 관련 API 문서 가독성 향상
- 게시글 검색 API 설명 수정
- 게시판 API에서 게시글 API로 검색 관련 API 이동
수정 후 API 문서 사진
> docs: 게시글 검색 관련 API 문서 수정

- src/main/resources/application.yml
resolve #170 
file 업로드 사이즈 변경
file 업로드 사이즈 변경
> fix: file 업로드 사이즈 변경

- src/main/java/com/sammaru5/sammaru/domain/User.java
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
- src/main/java/com/sammaru5/sammaru/web/controller/user/UserController.java
- src/main/java/com/sammaru5/sammaru/web/request/UserModifyRequestDto.java
resolve #182 
회원정보 수정 api 권한 변경 및 비밀번호 변경 api 추가
회원정보 수정 api 권한 변경 및 비밀번호 변경 api 추가
> fix: 회원정보 수정 api 권한 변경 및 비밀번호 api 추가

- src/main/java/com/sammaru5/sammaru/config/WebSecurityConfig.java
resolve #181
임시 비밀 번호 생성 api 접근권한 변경이 필요함
임시 비밀 번호 생성 api 접근권한 변경
> fix : 임시생성 비밀번호 api 접근 권한 변경

- src/main/java/com/sammaru5/sammaru/config/jwt/JwtAuthenticationFilter.java
- src/main/java/com/sammaru5/sammaru/config/jwt/JwtToken.java
- src/main/java/com/sammaru5/sammaru/config/jwt/TokenProvider.java
- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/service/user/UserLoginService.java
- src/main/java/com/sammaru5/sammaru/service/user/UserReissueService.java
- src/main/java/com/sammaru5/sammaru/web/controller/auth/AuthController.java
- src/main/java/com/sammaru5/sammaru/web/controller/auth/TokenRequest.java
- src/main/java/com/sammaru5/sammaru/web/dto/JwtDto.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
resolve #185 
application dev cookie secure 추가
application dev cookie secure 추가
> refactor: application dev cookie secure 추가

- src/main/java/com/sammaru5/sammaru/exception/ErrorCode.java
- src/main/java/com/sammaru5/sammaru/service/user/UserModifyService.java
resolve #191 
동일한 비밀번호로 변경 시 그대로 변경이 되던 현상이 존재
동일한 비밀번호로 변경 시 "동일한 비밀번호입니다." 오류 출력
> fix: 동일한 비밀번호로 변경 시 "동일한 비밀번호입니다" 오류 출력

- src/main/java/com/sammaru5/sammaru/config/WebSecurityConfig.java
resolve #194 
상용에서 swagger가 노출되지 않도록 수정
상용에서 swagger가 노출되지 않도록 수정
> fix: 상용에서 swagger가 노출되지 않도록 수정

- src/main/java/com/sammaru5/sammaru/config/WebSecurityConfig.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
resolve #194 
swagger pattern 매칭으로 변경
swagger pattern 매칭으로 변경
> fix: swagger pattern 매칭으로 변경

- build.gradle
- src/main/java/com/sammaru5/sammaru/aspect/LogAspect.java
- src/main/java/com/sammaru5/sammaru/aspect/LogELK.java
- src/main/resources/logback-spring.xml
resolve #200 
api에 대한 응답시간 및 호출횟수에 관한 로그 정보를 수집하기 위한 작업입니다.
* aop, logstash에 대한 의존성 추가
* api request log 저장
* logback-spring.xml 작성
sammaru-filebeat-%d{yyyy-MM-dd}.%i.log 에 api log저장
*  volume 설정 필요
*  SAMMARU/docker-compose-up.yml
*  SAMMARU/docker-compose-prod.yml
> feat : api 에 대한 logging 추가
